export const LOADING_END = 'LOADING_END'
export const LOADING_START = 'LOADING_START'
export const ERROR_SET = 'ERROR_SET'
export const ERROR_CLEAN = 'ERROR_CLEAN'
export const AUTH_SET = 'AUTH_SET'
export const USER_SET = 'USER_SET'
